export const TELEGRAM_MESSAGE_TIMEOUT_MS = 1000 * 60 * 15; 
export const COMMAND_TIMEOUT_MS = TELEGRAM_MESSAGE_TIMEOUT_MS - 1000;
export const REQUEST_TIMEOUT_MS = 1000 * 10;
export const SHUTDOWN_LOGOUT_TIMEOUT_MS = 1000;
